import React from "react"
import { Button } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/6FXbnJs6zGDavu8BOKPZ9a/Components-2?node-id=15%3A837",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        sm: "sm",
        md: "md",
        lg: "lg",
        xl: "xl",
        "2xl": "2xl",
      }),
      hierarchy: figma.enum("Hierarchy", {
        Primary: "primary",
        "Secondary color": "secondary-color",
        "Secondary gray": "secondary-gray",
        "Tertiary color": "tertiary-color",
        "Tertiary gray": "tertiary-gray",
        "Link color": "link-color",
        "Link gray": "link-gray",
      }),
      icon: figma.enum("Icon", {
        Default: "default",
        "Dot leading": "dot-leading",
      }),
      trailingIcon: figma.instance("🔀 Icon trailing swap"),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "iconLeading": figma.boolean('⬅️ Icon leading'),
      // "iconTrailing": figma.boolean('➡️ Icon trailing'),
      // "iconLeadingSwap": figma.instance('🔀 Icon leading swap'),
      // "iconTrailingSwap": figma.instance('🔀 Icon trailing swap')
    },
    example: (props) => (
      <Button
        size={props.size}
        hierarchy={props.hierarchy}
        icon={props.icon}
        trailingIcon={props.trailingIcon}
        disabled={props.disabled}
      />
    ),
  },
)
