import React from "react"
import { InputField } from "./InputField"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  InputField,
  "https://www.figma.com/design/6FXbnJs6zGDavu8BOKPZ9a/Components-2?node-id=33%3A8535",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        sm: "sm",
        md: "md",
      }),
      destructive: figma.boolean("Destructive"),
      required: figma.boolean("↳ Required *"),
      helpIcon: figma.boolean("Help icon"),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      type: figma.enum("Type", {
        "Trailing button": "button",
        "Leading text": "text",
        "Payment input": "month",
        Default: "url",
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.boolean('Label'),
      // "hintText": figma.boolean('Hint text'),
      // "helpIcon": figma.boolean('Help icon'),
      // "iconSwap": figma.instance('🔀 Icon swap'),
      // "required": figma.boolean('↳ Required *')
    },
    example: (props) => (
      <InputField
        size={props.size}
        destructive={props.destructive}
        required={props.required}
        helpIcon={props.helpIcon}
        disabled={props.disabled}
        type={props.type}
      />
    ),
  },
)
