import React from "react"
import { Toggle } from "./Toggle"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Toggle,
  "https://www.figma.com/design/6FXbnJs6zGDavu8BOKPZ9a/Components-2?node-id=33%3A2193",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        sm: "sm",
        md: "md",
      }),
      type: figma.enum("Type", {
        Default: "default",
        Slim: "slim",
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "supportingText": figma.boolean('Supporting text'),
      // "pressed": figma.boolean('Pressed'),
      // "text": figma.boolean('Text')
    },
    example: (props) => (
      <Toggle size={props.size} type={props.type} disabled={props.disabled} />
    ),
  },
)
